appid: 250307201
start: $JETTY_START
setenv: {'JVM_ARGS':'-Xms2048m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/logs/ -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Dmonitor_agent_app_id="$APPID"_"$INSTANCEID" -Denv=PRODUCT'}
tryRestart: 
    enable: true
    fail: 3
webHealth: true
webHealthConf: 
    path: /webHealth
    timeout: 2000ms
    success: [200,201,403,301,302]
tcpHealth: false